apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: brave-termite-go 
  janus-idp.io/tekton: brave-termite-go
  backstage.io/kubernetes-id: brave-termite-go
  backstage.io/kubernetes-namespace: flavius-e2e 
  app.kubernetes.io/part-of: brave-termite-go
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  