apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: brave-termite-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: brave-termite-go 
  name: brave-termite-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: brave-termite-go 
